# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Onedata Blog'
tagline:             'News form Onedata Space'
description:         'News form Onedata Space!'
url:                 http://groundnuty.github.io/oneblog/
baseurl:             'http://groundnuty.github.io/oneblog/'
paginate:            5

# About/contact
author:
  name:              Onedata
  url:               www.onedata.org
  email:             onedata@cyfronet.pl

# Custom vars
version:             1.0.0
